fmod NEW-TERM is protecting META-LEVEL .


op subterms : TermList -> TermList .
eq subterms(empty) = empty .
eq subterms(C:Constant) = C:Constant .
eq subterms(V:Variable) = V:Variable .
eq subterms(Q:Qid[TL:TermList]) = Q:Qid[TL:TermList], subterms(TL:TermList) .
eq subterms((T:Term, TL:TermList)) = subterms(T:Term), subterms(TL:TermList) .
endfm


red subterms('_+_['_*_['Y:Nat,'s_^5['0.Zero]],'gcd['X:Nat,'s_^100['0.Zero]]]) .
